name: test-evowit
options:
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: 5.0
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    DEVELOPMENT_TEAM: 76PHSCHPCK
    CODE_SIGN_STYLE: Automatic
packages: {}
schemes:
  TestEvowit:
    build:
      targets:
        TestEvowit: all
targets:
  TestEvowit:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - TestEvowit
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.we555.test-evowit
        INFOPLIST_FILE: TestEvowit/Info.plist
        PRODUCT_NAME: test-evowit
        TARGETED_DEVICE_FAMILY: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
    info:
      path: TestEvowit/Info.plist
      properties:
        CFBundleDisplayName: test-evowit
        UILaunchScreen: {}
        NSCameraUsageDescription: Allow camera access to capture homework questions.
        NSPhotoLibraryUsageDescription: Allow photo access to import homework images.
        NSPhotoLibraryAddUsageDescription: Allow photo library access to save solved screenshots.
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        BACKEND_BASE_URL: http://120.197.118.22:21080
